mysql:
  dsn:
    host: localhost
    port: 3306
    db: wordpress
    user: root
    password: root
    charset: utf8mb4
  pool:
    # 最长空闲时间
    connMaxIdleTime: 60
    # 最大连接数
    maxOpenConn: 100
    # 最大空闲连接数
    maxIdleConn: 10
    # 连接的生命时长
    connMaxLifetime: 236
# 最近文章缓存时间
recentPostCacheTime: 5m
# 分类缓存时间
categoryCacheTime: 5m
# 上下篇缓存时间
contextPostCacheTime: 10h
# 最近评论缓存时间
recentCommentsCacheTime: 5m
# 摘要缓存时间
digestCacheTime: 5m
# 摘要字数
digestWordCount: 300
# 文档列表id页缓存 包括默认列表、分类
postListCacheTime: 1h
# 搜索文档id缓存时间
searchPostCacheTime: 5m
# 月归档文章id缓存时间
monthPostCacheTime: 1h
# 文档数据缓存时间
postDataCacheTime: 1h
# 文章评论缓存时间
commentsCacheTime: 5m
# 定时清理缓存周期时间
crontabClearCacheTime: 5m
# 到达指定并发请求数时随机sleep
maxRequestSleepNum: 100
# 随机sleep时间
sleepTime: [1s,3s]
# 全局最大请求数，超过直接403
maxRequestNum: 500
# 单ip同时最大搜索请求数
singleIpSearchNum: 10
# 文档最大id缓存时间
maxPostIdCacheTime: 1h
