mysql:
  dsn:
    host: localhost
    port: 3306
    db: wordpress
    user: root
    password: root
    charset: utf8mb4
  pool:
    # 最长空闲时间
    connMaxIdleTime: 60
    # 最大连接数
    maxOpenConn: 100
    # 最大空闲连接数
    maxIdleConn: 10
    # 连接的生命时长
    connMaxLifetime: 236
# 最近文章缓存时间
recentPostCacheTime: 5m
# 分类缓存时间
categoryCacheTime: 5m
# 上下篇缓存时间
contextPostCacheTime: 10h
# 最近评论缓存时间
recentCommentsCacheTime: 5m
# 摘要缓存时间
digestCacheTime: 5m
# 摘要字数
digestWordCount: 300
